### 데이터 (입력 x, 정답 t)에 대한 Linear Regression (Simple)

오차를 계산하기 위해서는 training data의 모든 입력 x에 대한 각각의 y = Wx + b 계산 해야 함 
=> 이때, 입력 x, 정답 t, 가중치 W 모두 행렬로 나타낸 후에 행렬 곱 (dot product)을 이용하면 
계산 값 y 또한 행렬로 표시되어 모든 입력 데이터에 대해 한번에 쉽게 계산되는 것을 알 수 있다 

##### 학습 데이터 준비 

In [1]:
import numpy as np

x_data = np.array([1, 2, 3, 4, 5]).reshape(5,1)
t_data = np.array([2, 3, 4, 5, 6]).reshape(5,1) 

# raw_data = [ [1, 2], [2, 3], [3, 4], [4, 5], [5, 6] ]

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (5, 1) , t_data.shape =  (5, 1)


##### 임의의 직선  y = Wx + b 정의  (임의이 값으로 가중치 W, 바이어스 b 초기화)

In [2]:
W = np.random.rand(1,1)  
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.95595834]] , W.shape =  (1, 1) , b =  [0.60628513] , b.shape =  (1,)


##### 손실 함수 E(w, b) 정의 

In [3]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2))/ (len(x))

#### 수치 미분 (numerical_derivative) 및 utility 함수 정의 

In [4]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [5]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x,W) + b
    
    return (np.sum((t - y)**2))/ (len(x))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x,W) + b
    
    return y

##### 학습률 (Learning rate) 초기화 및 손실함수가 최소가 될 때까지 W, b 업데이트

In [6]:
learning_rate = 1e-2  # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(8001):  
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  0.2803868722332239 Initial W =  [[0.95595834]] 
 , b =  [0.60628513]
step =  0 error value =  0.17444098503004232 W =  [[0.9892704]] , b =  [0.6148032]
step =  400 error value =  0.0015156692324042223 W =  [[1.02528127]] , b =  [0.90874892]
step =  800 error value =  9.670865762268464e-05 W =  [[1.00638601]] , b =  [0.97695013]
step =  1200 error value =  6.170584095286451e-06 W =  [[1.00161309]] , b =  [0.99417764]
step =  1600 error value =  3.937197456043207e-07 W =  [[1.00040747]] , b =  [0.99852928]
step =  2000 error value =  2.5121647429919568e-08 W =  [[1.00010292]] , b =  [0.9996285]
step =  2400 error value =  1.6029096245043324e-09 W =  [[1.000026]] , b =  [0.99990616]
step =  2800 error value =  1.0227511040426372e-10 W =  [[1.00000657]] , b =  [0.9999763]
step =  3200 error value =  6.525756692793737e-12 W =  [[1.00000166]] , b =  [0.99999401]
step =  3600 error value =  4.163818567827739e-13 W =  [[1.00000042]] , b =  [0.99999849]
step =  4000 error

In [7]:
predict(43) 

array([[44.]])

### 데이터 (입력 x1, x2, x3, 정답 t)에 대한 regression (multi-variable)

##### 학습데이터 

In [8]:
import numpy as np

loaded_data = np.loadtxt('./data_regression.csv', delimiter=',', dtype=np.float32)
loaded_data[0]

array([ 73.,  80.,  75., 152.], dtype=float32)

In [9]:
x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


In [10]:
W = np.random.rand(3,1)  # 3X1 행렬
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.9709763 ]
 [0.4445024 ]
 [0.01355926]] , W.shape =  (3, 1) , b =  [0.9267548] , b.shape =  (1,)


##### 손실함수, 수치미분 등  simple 과 동일한 processing

##### 학습률 (Learning rate) 초기화 및 손실함수가 최소가 될 때까지 W, b 업데이트 

In [11]:
learning_rate = 1e-5  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(10001):     
    W -= learning_rate * numerical_derivative(f, W)  
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  2371.758133663627 Initial W =  [[0.9709763 ]
 [0.4445024 ]
 [0.01355926]] 
 , b =  [0.9267548]
step =  0 error value =  896.1281937675925 W =  [[1.04808676]
 [0.52211577]
 [0.09344957]] , b =  [0.92733801]
step =  400 error value =  24.567648994045 W =  [[1.08864793]
 [0.59594736]
 [0.33975076]] , b =  [0.92844144]
step =  800 error value =  20.18574638719309 W =  [[1.01715718]
 [0.55945483]
 [0.44488977]] , b =  [0.92850502]
step =  1200 error value =  16.91715674365405 W =  [[0.95276014]
 [0.53132239]
 [0.53496655]] , b =  [0.92845195]
step =  1600 error value =  14.464561882864835 W =  [[0.89473423]
 [0.5099583 ]
 [0.61223861]] , b =  [0.92829878]
step =  2000 error value =  12.613128279713894 W =  [[0.84243337]
 [0.49405204]
 [0.67861431]] , b =  [0.92805958]
step =  2400 error value =  11.20699722068106 W =  [[0.7952795 ]
 [0.48252635]
 [0.73570803]] , b =  [0.92774638]
step =  2800 error value =  10.13259816818354 W =  [[0.75275498]
 [0.47449737]
 [0.784886

In [12]:
test_data = np.array([100, 98, 81])

predict(test_data) 

array([179.68916317])