### 수치미분 

In [7]:
# f : 미분하려는 함수, 외부에서 def, lambda등으로 정의 
# x : 미분 값을 알고자 하는 입력 값, 즉 미세하게 변하는 입력 값

def numerical_derivative(f, x):
    delta_x = 1e-4 # lim에 해당되는 작은 값
    
    return (f(x + delta_x) - f(x-delta_x)) / (2 * delta_x)

##### 예제 1
- 함수 f(x) = x^2 에서 미분계수 f`(3)을 구하기, 즉 x =3에서 값이 미세하게 변할 때, 함수 f는 얼마나 변하는지 계산하라는 의미

In [9]:
def my_func1(x):
    return x**2

In [10]:
result = numerical_derivative(my_func1, 3)
print(f"result == {result}")

result == 6.000000000012662


##### 예제2 
- 함수 f(x) =3xe^x 에서 미분계수 f`(3)을 구하기, 즉 x =2에서 값이 미세하게 변할 때, 함수 f는 얼마나 변하는지 계산하라는 의미

In [12]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

In [13]:
result = numerical_derivative(my_func2, 2)
print(f"result == {result}")

result == 66.50150507518049


##### 다 변수 함수
- 입력 변수가 하나 이상인 다 변수 함수의 경우, 입력 변수는 서로 독립적이기 때문에 수치미분 도는 변수의 개수만큼 개별적으로 계산해야 한다 

    - [insight] f(x,y) = 2x + 3xy + y^3 인 경우 
    - f`(1.0, 2.0) = (8.0, 15,0) 직관적 이해 
    - x = 1.0에서 미분 값을 구한다는 것은, 값은 2.0으로 고정한 상태에서 y = 1.0을 미세하게 변화시킬 때 f(x,y)는 얼마나 변화하는지 알아보겠다는 의미, 즉 y = 2.0으로 고정된 상태에서 x = 1.0을 미세하게 변화시키면 f(x,y)는 8.0만큼 변한다는 의미
    - y = 2.0에서 미분 값을 구한다는 것은, 값은 1.0으로 고정한 상태에서 y = 2.0을 미세하게 변화시킬 때 f(x,y)는 얼마나 변화하는지 알아보겠다는 의미, 즉 x = 1.0으로 고정된 상태에서 y = 2.0을 미세하게 변화시키면 f(x,y)는 15.0만큼 변한다는 의미

In [17]:
import numpy as np

# f : 다변수 함수
# x : 모든 변수를 포함하고 있는 numpy 객체 (배열, 행렬)
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x) # 계산된 수치미분 값 저장 변수
    print("debug 1. initial input variable =", x) # 모든 입력 변수  
    print("debug 2. initial grad =", grad) # 모든 입력 변수의 미분 값 초기화
    print("=======================================")
    
    # 모든 입력 변수에 대해 편미분하기 위한 iterator 획득
    it = np.nditer(x, flags=['multi_index'], op_flags = ['readwrite'])
    
    # 변수의 개수 만큼 반복
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])  
        
        tmp_val = x[idx] # numpy 타입은 mutable 이므로 원래 값 보관
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)

        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx]) # 계산된 미분값
        print("debug 5. grad = ", grad) # 계산됨 모든 미분값
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

##### 다변수함수 예제 1
- 1 변수 함수 f(x) = x**2, f`(3.0)

In [19]:
def func1(input_obj):    
    x = input_obj[0]
    
    return  x**2  

In [20]:
# x = 3.0 에서의 편미분 값
numerical_derivative( func1, np.array([3.0]) ) 

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]


array([6.])

##### 다변수 함수 예제2
- 2 변수 함수 f(x,y) = 2x + 3xy + y**3, f`(1.0, 2.0)

In [25]:
def func1(input_obj):    
    x = input_obj[0]
    y = input_obj[1]
    
    return  (2*x + 3*x*y + np.power(y,3))  

In [26]:
input = np.array([1.0, 2.0])
numerical_derivative( func1, input ) 

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

##### 편미분 예제 
- 2 변수 함수 f(w,x,y,z) = wx + xyz + 3w + zy**2, f`(1.0, 2.0, 3.0, 4.0)

In [28]:
def func1(input_obj):    
    w = input_obj[0, 0]
    x = input_obj[0, 1]
    y = input_obj[1, 0]
    z = input_obj[1, 1]
    
    return  (w*x + x*y*z + 3*w + z*np.power(y,3))  

In [30]:
input = np.array([[1.0, 2.0], [3.0, 4.0]])
numerical_derivative( func1, input ) 

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  4.999999999881766
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  13.000000000147338
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  116.00000004023059
debug 5. grad =  [[  5.          13.        ]
 [116.00000004   0.        ]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  32.99999999995862
debug 5. grad =  [[  5.          13.        ]
 [116.00000004  33.        ]]


array([[  5.        ,  13.        ],
       [116.00000004,  33.        ]])